"""Generate a repository-wide Python code reference from the AST."""

from __future__ import annotations

import ast
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

ROOTS = (Path("src"), Path("tests"), Path("scripts"))
OUTPUT_PATH = Path("docs/code-reference.md")


@dataclass(frozen=True)
class SymbolInfo:
    """One documented top-level symbol."""

    kind: str
    signature: str
    doc_summary: str | None


@dataclass(frozen=True)
class FileInfo:
    """One documented Python file."""

    path: Path
    purpose: str
    module_docstring_present: bool
    symbols: tuple[SymbolInfo, ...]


def iter_python_files(roots: Iterable[Path]) -> tuple[Path, ...]:
    """Return every Python file under the configured roots in sorted order."""
    files = {path for root in roots for path in root.rglob("*.py")}
    return tuple(sorted(files))


def summarize_docstring(docstring: str | None) -> str | None:
    """Collapse a docstring down to its first non-empty sentence-like line."""
    if not docstring:
        return None
    for line in docstring.strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return None


def infer_purpose(path: Path, module_doc_summary: str | None) -> str:
    """Infer a human-readable file purpose when a module docstring is absent."""
    if module_doc_summary:
        return module_doc_summary
    stem = path.stem
    if path.parts[0] == "tests":
        if stem == "conftest":
            return "Pytest fixtures and shared test helpers."
        if stem.startswith("test_"):
            words = stem.removeprefix("test_").replace("_", " ")
            return f"Tests covering {words} behavior."
    if path.parts[0] == "scripts":
        words = stem.replace("_", " ")
        return f"Utility script for {words}."
    return "No module docstring; see top-level symbols below."


def format_function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Render a compact function signature from AST arguments."""
    parts: list[str] = []
    positional = [arg.arg for arg in node.args.posonlyargs]
    regular = [arg.arg for arg in node.args.args]
    defaults = len(node.args.defaults)
    regular_no_defaults = len(regular) - defaults

    for index, name in enumerate(positional):
        suffix = "=..." if index >= len(positional) - max(0, defaults - len(regular)) else ""
        parts.append(f"{name}{suffix}")
    if positional:
        parts.append("/")

    for index, name in enumerate(regular):
        suffix = "=..." if index >= regular_no_defaults else ""
        parts.append(f"{name}{suffix}")

    if node.args.vararg is not None:
        parts.append(f"*{node.args.vararg.arg}")
    elif node.args.kwonlyargs:
        parts.append("*")

    for arg, default in zip(node.args.kwonlyargs, node.args.kw_defaults, strict=True):
        suffix = "=..." if default is not None else ""
        parts.append(f"{arg.arg}{suffix}")

    if node.args.kwarg is not None:
        parts.append(f"**{node.args.kwarg.arg}")

    return f"{node.name}({', '.join(parts)})"


def file_info(path: Path) -> FileInfo:
    """Parse one Python file into documentation metadata."""
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text, filename=str(path))
    module_doc = ast.get_docstring(tree)
    module_doc_summary = summarize_docstring(module_doc)
    symbols: list[SymbolInfo] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            symbols.append(
                SymbolInfo(
                    kind="class",
                    signature=node.name,
                    doc_summary=summarize_docstring(ast.get_docstring(node)),
                )
            )
        elif isinstance(node, ast.FunctionDef):
            symbols.append(
                SymbolInfo(
                    kind="function",
                    signature=format_function_signature(node),
                    doc_summary=summarize_docstring(ast.get_docstring(node)),
                )
            )
        elif isinstance(node, ast.AsyncFunctionDef):
            symbols.append(
                SymbolInfo(
                    kind="async function",
                    signature=format_function_signature(node),
                    doc_summary=summarize_docstring(ast.get_docstring(node)),
                )
            )
    return FileInfo(
        path=path,
        purpose=infer_purpose(path, module_doc_summary),
        module_docstring_present=module_doc is not None,
        symbols=tuple(symbols),
    )


def render_markdown(files: tuple[FileInfo, ...]) -> str:
    """Render the complete code reference document."""
    root_counts = {
        root.name: sum(1 for info in files if info.path.parts[0] == root.name)
        for root in ROOTS
    }
    lines = [
        "# Code Reference",
        "",
        "This file is generated by `python scripts/generate_code_reference.py`.",
        "It inventories every Python file under `src/`, `tests/`, and `scripts/`.",
        "",
        "## Coverage",
        "",
        f"- Total Python files: `{len(files)}`",
        f"- `src/`: `{root_counts['src']}`",
        f"- `tests/`: `{root_counts['tests']}`",
        f"- `scripts/`: `{root_counts['scripts']}`",
        "",
        "## File Inventory",
        "",
    ]

    current_root: str | None = None
    for info in files:
        root = info.path.parts[0]
        if root != current_root:
            current_root = root
            lines.extend([f"### `{root}/`", ""])

        lines.extend(
            [
                f"#### `{info.path.as_posix()}`",
                "",
                f"- Purpose: {info.purpose}",
                f"- Module docstring: `{'yes' if info.module_docstring_present else 'no'}`",
            ]
        )
        if info.symbols:
            lines.append("- Top-level symbols:")
            for symbol in info.symbols:
                suffix = symbol.doc_summary or "No symbol docstring."
                lines.append(f"  - `{symbol.kind} {symbol.signature}`: {suffix}")
        else:
            lines.append("- Top-level symbols: none")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    """Generate the checked-in code reference markdown file."""
    files = tuple(file_info(path) for path in iter_python_files(ROOTS))
    OUTPUT_PATH.write_text(render_markdown(files), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
